### ISSUE TITLE
Gradle workflow for Lambda with layers produces weird classpath

### ISSUE THREAD

**Issue by noavarice** [aws/aws-lambda-builders#231]
**Gradle build workflow for AWS::Serverless::LayerVersion produces same output as for AWS::Serverless::Function**
It's more of a question because I didn't manage to find enough information on this subject.
Consider you want to test Lambda function with layer being built locally (there's a [small repo](https://github.com/noavarice/aws-sam-layered-lambda-example) to reproduce the issue, just run `sam build` and launch function):
1. Create Gradle project.
2. Create submodule with layer code.
3. Create submodule with function code relying on layer as `compileOnly` dependency - assuming that layer classpath will be supplied through AWS facilities (UI, CLI, etc).
4. Execute function locally

**Observed result:** function executes successfully.

**Expected result:** function fails with `NoClassDefFoundError`.
Launching function from mentioned example repo prints contents of `/opt` directory and tries to execute layer code. It gives the following result:
```
/opt/java/META-INF/MANIFEST.MF
/opt/java/org/example/math/MathOps.class
/opt/java/lib/jackson-annotations-2.12.3.jar
/opt/java/lib/jackson-core-2.12.3.jar
/opt/java/lib/jackson-databind-2.12.3.jar
org/example/math/MathOps: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/example/math/MathOps
	at org.example.function.LambdaFunction.handleRequest(LambdaFunction.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.example.math.MathOps. Current classpath: file:/var/task/:file:/var/task/lib/aws-lambda-java-core-1.2.0.jar:file:/opt/java/lib/jackson-annotations-2.12.3.jar:file:/opt/java/lib/jackson-core-2.12.3.jar:file:/opt/java/lib/jackson-databind-2.12.3.jar
```
As you can see, `MathOps` is placed as class file inside of `/opt/java` rather than JAR inside of `/opt/java/lib`. AFAIU it's because `AWS::Serverless::LayerVersion` is being built just like `AWS::Serverless::Function` while it probably should not. Question is - is it a problem with project setup, a lack of understanding of how AWS SAM works under the hood or a bug indeed?

**Additional environment details**
* OS Ubuntu 20.04
* `sam --version`: `SAM CLI, version 1.22.0`
* Gradle version - as specified in wrapper properties

**Comment by mndeveci** [comment]
Thanks for reporting this issue @noavarice !

We've made some changes to our java builders recently, I wanted to check if those changes will resolve your issue. When I cloned your repository and run `sam build && sam local invoke` I was able to get following result;
```
START RequestId: 56ca138d-784f-4073-8dad-436a6ab1766c Version: $LATEST
/opt/java/lib/jackson-annotations-2.12.3.jar
/opt/java/lib/math.jar
/opt/java/lib/jackson-databind-2.12.3.jar
/opt/java/lib/jackson-core-2.12.3.jar
END RequestId: 56ca138d-784f-4073-8dad-436a6ab1766c
REPORT RequestId: 56ca138d-784f-4073-8dad-436a6ab1766c	Init Duration: 0.30 ms	Duration: 354.88 ms	Billed Duration: 355 ms	Memory Size: 512 MB	Max Memory Used: 512 MB
16%
```

I just needed to change your function code into this (not sure why but it was failing with issue with de-serializing);
```
public class LambdaFunction implements RequestHandler<Object, Integer> {

    @Override
    public Integer handleRequest(final Object input, final Context context) {
        try {
            Files.walk(Paths.get("/opt"))
                    .filter(Files::isRegularFile)
                    .forEach(System.out::println);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return MathOps.quad(4);
    }
}
```

Please let us know if you still encounter the issue.
