### ISSUE TITLE
Lambda application return error with libjvm.so, for a node js application

### ISSUE THREAD

**Issue by Krishman23** [aws/aws-lambda-builders#367]
I have a node js application, which uses xslt4node package.
[](https://github.com/Krishman23/xslt-transform/blob/main/xslt-transform/app.js)
After successful deployment from SAM Cli, im getting below errror.

```
{
    "errorType": "Error",
    "errorMessage": "libjvm.so: cannot open shared object file: No such file or directory",
    "code": "ERR_DLOPEN_FAILED",
    "stack": [
        "Error: libjvm.so: cannot open shared object file: No such file or directory",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at Object.<anonymous> (/var/task/node_modules/java/lib/nodeJavaBridge.js:21:16)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
    ]
}

```

**Comment by moelasmar** [comment]
I did some investigation for this issue, and I found the following:
 - Your package depends on `xslt4node` which depends on `java`. You can find your package dependency [here](https://github.com/Krishman23/xslt-transform/blob/main/xslt-transform/package.json#L10), and the `xslt4node` dependencies [here](https://github.com/e2ebridge/xslt4node/blob/master/package.json#L6)
 - I found this issue raised before for the `node-java` repo [here](https://github.com/joeferner/node-java/issues/306), and [here](https://stackoverflow.com/questions/36191073/node-java-error-libjvm-so-cannot-open-shared-object-file-no-such-file-or-dire). Based on the solutions mentioned in the previous posts, you need to set the `JAVA_HOME` environment variable.
 - Java will not be installed by default in the Lambda function, and so you need to provide it through a lambda layer function, then you can set the value of the java home environment variable.

**Comment by moelasmar** [comment]
based on the previous investigation, I do not think that this issue is related to SAM Builders.

**Comment by moelasmar** [comment]
sorry @Krishman23 I do not have enough info about doing that. Let me do some investigations and I will come back to you with some approach.

My feelings is using the Image type Lambda function will be easier in this case, as you can control what will exist in the running container. Do you have any preference on using the ZIP type lambda functions, or you are OK with both options ?

**Comment by moelasmar** [comment]
@Krishman23 .. were you able to find a way to include the java binaries in the lambda function layers?
